# Generated by Django 5.2.5 on 2025-08-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=2000)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
